#!/bin/sh
# Validate exact domain-generated bytes without the lab entrypoint or volumes.
set -eu
root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
image=${LAB_IMAGE:-xkeen-router-lab:dev}
work=$(mktemp -d "${TMPDIR:-/tmp}/xkeen-catalog.XXXXXX")
trap 'rm -rf "$work"' EXIT HUP INT TERM
docker image inspect "$image" >/dev/null
version=$(docker run --rm --network none --read-only --entrypoint /opt/sbin/xray "$image" version)
case "$version" in
  'Xray 26.3.27 '*) ;;
  'Xray 26.3.27') ;;
  *) echo 'validation unavailable: expected Xray 26.3.27' >&2; exit 1 ;;
esac
printf '%s\n' "$version"
mkdir "$work/positive" "$work/negative"
(cd "$root" && "${GO:-go}" build -o "$work/demo" ./cmd/xkeen-config-demo)
"$work/demo" -dir "$work/positive"
"$work/demo" -dir "$work/negative" -invalid-protocol

checksums() {
  (cd "$1" && shasum -a 256 ./*.json)
}
validate() {
  docker run --rm --network none --read-only \
    --mount "type=bind,src=$1,dst=/candidate,readonly" \
    --entrypoint /opt/sbin/xray "$image" run -test -format json -confdir /candidate
}
for variant in positive negative; do
  dir="$work/$variant"
  set -- "$dir"/*
  [ "$#" -eq 6 ] || { echo 'unexpected catalog files' >&2; exit 1; }
  for name in 01_log.json 02_api.json 03_inbounds.json 04_outbounds.json 05_routing.json 06_extra.json; do
    [ -f "$dir/$name" ] || { echo "missing $name" >&2; exit 1; }
  done
  before=$(checksums "$dir")
  if [ "$variant" = positive ]; then
    validate "$dir" > "$work/positive.log" 2>&1 || { cat "$work/positive.log" >&2; exit 1; }
    echo 'positive: PASS'
  else
    if validate "$dir" > "$work/negative.log" 2>&1; then
      echo 'negative: false success' >&2; exit 1
    fi
    # A failed launch or mount must not masquerade as a configuration rejection.
    if ! grep -Fq 'invalid-demo-protocol' "$work/negative.log"; then
      cat "$work/negative.log" >&2; echo 'negative: validator unavailable' >&2; exit 1
    fi
    echo 'negative: rejected invalid-demo-protocol'
  fi
  after=$(checksums "$dir")
  [ "$before" = "$after" ] || { echo 'candidate bytes changed' >&2; exit 1; }
  printf '%s\n' "$variant SHA256:" "$after"
done
